default_chain: stride-testnet
chains:
  gaia-testnet:
    key: gaiad
    chain-id: GAIA
    rpc-addr: http://149.102.143.60:26657
    grpc-addr: http://149.102.143.60:9090
    account-prefix: cosmos
    keyring-backend: test
    gas-adjustment: 1.2
    gas-prices: 0.001uatom
    key-directory: /root/.icq/keys
    debug: false
    timeout: 20s
    block-timeout: ""
    output-format: json
    sign-mode: direct
  stride-testnet:
    key: fazilwallet
    chain-id: STRIDE-TESTNET-4
    rpc-addr: http://38.242.159.20:26657
    grpc-addr: http://38.242.159.20:9090
    account-prefix: stride
    keyring-backend: test
    gas-adjustment: 1.2
    gas-prices: 0.001ustrd
    key-directory: /root/.icq/keys
    debug: false
    timeout: 20s
    block-timeout: ""
    output-format: json
    sign-mode: direct
cl: {}
